# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
 # Box settings:

  config.vm.box = "ubuntu/trusty64"


  # config.vm.box_check_update = false

# Network Settings:

  #config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "10.10.10.10"
  # config.vm.network "public_network"

 
 # Shared Folder settings:

 config.vm.synced_folder ".", "/var/www/html/"

# Provider settings:

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  vb.memory = "1024"
  vb.cpus = "4"
  end

# Provision settings:

  config.vm.post_up_message="Web App running on 10.10.10.10"
  config.vm.provision "shell", path: "script.sh"
  #config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #  apt-get install -y apache2
  # SHELL
end
